### ISSUE TITLE
discord token login broken

### ISSUE THREAD

**Issue by Brandon981026** [hxr404/Discord-Console-hacks#41]

**Comment by vooktm** [comment]
the token login is being depreciated afaik

**Comment by Raz-js** [comment]
> the token login is being depreciated afaik

Rip

**Comment by hxr404** [comment]
> the token login is being depreciated afaik

You are mostly right. The token login stopped working in the Desktop Client, but it should continue to work in browsers. I don't have much time and I currently focus on [Discord Oxygen](https://github.com/hxr404/Discord-Oxygen), that's why only Firefox/Tor Browser are officially supported by this project.
