### ISSUE TITLE
Misleading information

### ISSUE THREAD

**Issue by CanadaHonk** [hxr404/Discord-Console-hacks#45]
The README states:
> Discord acts as a MITM (Intercepts your traffic and decrypts your messsages)

Discord doesn't intercept your traffic.. it just gets sent to their servers. It doesn't decrypt messages as they are never encrypted, Discord doesn't have / use End to End Encryption. (Unless you mean HTTPS? In which case that is every web server?)

**Comment by Anonymous941** [comment]
I think it is referring to [this article](https://medium.com/tenable-techblog/lets-reverse-engineer-discord-1976773f4626).

**Comment by hxr404** [comment]
> The README states:
> 
> > Discord acts as a MITM (Intercepts your traffic and decrypts your messsages)
> 
> Discord doesn't intercept your traffic.. it just gets sent to their servers. It doesn't decrypt messages as they are never encrypted, Discord doesn't have / use End to End Encryption. (Unless you mean HTTPS? In which case that is every web server?)

Yes, you are absolutely right, most messages aren't encrypted in discord (except if you'd consider https which I don't), but the thing is, Discord claims that they encrypt messages.
Voice & audio data are theoretically encrypted though, and as @Anonymous941 stated

> I think it is referring to [this article](https://medium.com/tenable-techblog/lets-reverse-engineer-discord-1976773f4626).

that paragraph on my README is referring to said article. 


English isn't my first language, so if there's something that can be improved feel free to open a PR.

**Comment by hxr404** [comment]
Well actually I think I might know where the misunderstanding is.
It's about "intercepting traffic". That might suggest Discord is intercepting traffic it shouldn't have access to.
What I was trying to say is, that they "intercept" messages (read & process them before passing them to the receiver, but it's not only about messages, but about voice & video calls and that's which is why I said traffic, I now recognize that it really wrong usage of the word.

So I apologize for using misleading language / for the wrong usage of that term.
Thanks a lot for pointing it out, I probably wouldn't have noticed.

I'll fix it asap
