### ISSUE TITLE
Hidden channels

### ISSUE THREAD

**Issue by FarisBlayz** [hxr404/Discord-Console-hacks#46]
Hello, The hidden channel script example is an image, Please can you give me the script since I can't copy the script off an image, Thanks.

**Comment by FarisBlayz** [comment]
I figured it out lol you can close the issue,

**Comment by FarisBlayz** [comment]
By the way what can you do with these ID's? Like is it possible to view them or what exactly can you do with the private hidden channel discord ID's?

**Comment by hxr404** [comment]
> By the way what can you do with these ID's? Like is it possible to view them or what exactly can you do with the private hidden channel discord ID's?

Well for example you could get the Name of the channels or view who can access them / who has which perms, you won't be able to access the channels contents.
Questions like these might be better suited in the discord server, invite is on the readme.

Since your original question is resolved I'll close this now.

**Comment by 13-05** [comment]
somewhat irrelevant, but hxr's snippet actually displays dms rather than hidden channels

if you want hidden channels, you can roughly compare `getMutableGuildChannelsForGuild("GUILD")` and `getChannels("GUILD")`

the snippet below shows how to get the ids of hidden channels
```js
function getHiddenChannelIds(guildID) { // guildID should be type "string", btw
    let mod;
    let visibleChannels = [];
    let hiddenChannels = [];
    window.webpackChunkdiscord_app.push([[Math.random()],{},(e)=>{mod=mod||Object.values(e.c).find(m=>m?.exports?.default&&m.exports.default["getMutableGuildChannelsForGuild"])}]);
    let allChannels = Object.keys(mod.exports.default.getMutableGuildChannelsForGuild(guildID));
    mod = undefined;
    window.webpackChunkdiscord_app.push([[Math.random()],{},(e)=>{mod=mod||Object.values(e.c).find(m=>m?.exports?.default&&m.exports.default["getChannels"])}]);
    mod.exports.default.getChannels(guildID)["SELECTABLE"].forEach(o => visibleChannels.push(o.channel.id));
    mod = undefined;
    window.webpackChunkdiscord_app.push([[Math.random()],{},(e)=>{mod=mod||Object.values(e.c).find(m=>m?.exports?.default&&m.exports.default["hasChannel"])}]);
    allChannels.filter(hiddenChannel => visibleChannels.every(visibleChannel => visibleChannel != hiddenChannel)).forEach(channelId => hiddenChannels.push(mod.exports.default.getChannel(channelId))); // takes visible channels away from all channels, leaving us with non-visible ("hidden") channels
    mod = undefined;
    return hiddenChannels.filter(channelObj => channelObj.isCategory() == false); // makes sure no categories are falsely flagged as hidden channels
}
```
note that some parts (`window.webpackChunkdiscord_app.push`es, mainly) have been minified so the function doesnt seem even bigger
